version: '3.4'

services:
  spring_app:
      container_name: spring_app
      build: .
      ports:
       - "9090:8080"
      networks:
        vpcbr:
          ipv4_address: 172.19.0.5

  mongo:
    container_name: mongo
    image: "mongo:latest"
    ports:
     - "32769:27017"
    networks:
      vpcbr:
        ipv4_address: 172.19.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.3/16